# 端口
server:
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  # 原本是8000端口，远程微服务一直调用不到，换了其他端口就可以了!!!
  port: 8888
spring:
  application:
    name: gulimall-member
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///gulimall_ums?serverTimezone=GMT%2B8
    username: root
    password: 123

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  # xml文件位置配置
  mapper-locations: classpath:/mapper/*Dao.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
