server:
  port: 10000     # 端口

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.27.130:3306/gulimall_pms
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    username: root
    password: 123

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*Dao.xml                # xml文件位置配置
  global-config:
    db-config:
      id-type: auto                                           # 主键自增
      logic-delete-value: 1                                   # 逻辑已删除
      logic-not-delete-value: 0                               # 逻辑未删除

logging:
  level:
    com.zzx.gulimall: debug