# 端口
server:
  port: 9000

# 线程池的配置
gulimall:
  config:
    thread:
      core-pool-size: 20
      maximum-pool-size: 200
      keep-alive-time: 10

spring:
  application:
    name: gulimall-order


  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///gulimall_oms?serverTimezone=GMT%2B8
    username: root
    password: 123

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  # xml文件位置配置
  mapper-locations: classpath:/mapper/*Dao.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
