# 端口
server:
  port: 11000

spring:
  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///gulimall_wms?serverTimezone=GMT%2B8
    username: root
    password: 123

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  rabbitmq:
    host: localhost
    virtual-host: /
    listener:
      simple:
        # 手动ack
        acknowledge-mode: manual


mybatis-plus:
  # xml文件位置配置
  mapper-locations: classpath:/mapper/*Dao.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.zzx: debug
