# 端口
server:
  port: 11000

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.27.130:3306/gulimall_wms
    username: root
    password: 123

mybatis-plus:
  # xml文件位置配置
  mapper-locations: classpath:/mapper/*Dao.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
